#!/bin/bash
if [[ -n $XDG_CONFIG_DIR && ! -z $XDG_CONFIG_DIR ]]; then
    rm -rf "$XDG_CONFIG_DIR/git-loc-history.conf"
else
    rm -rf /home/*/.config/git-loc-history.conf
fi
rm -rf /var/cache/git-loc-history